### ISSUE TITLE
Piracy

### ISSUE THREAD

**Issue by zbzoll** [spitalnyd/spitalnyd.github.io#4]
the conclusion is not fully updated yet make sure you update it so it's included

**Comment by spitalnyd** [comment]
I just finshed thakyou

**Comment by spitalnyd** [comment]
Fix your formatting alitttle

**Comment by zbzoll** [comment]
nice nice

**Comment by zbzoll** [comment]
i fixed it

**Comment by spitalnyd** [comment]
anything else

**Comment by zbzoll** [comment]
i dont see anything else but i will check

**Comment by zbzoll** [comment]
looks good
